### ISSUE TITLE
What is the id in stats function? 

### ISSUE THREAD

**Issue by JubayerAhmedSagor** [StarkBotsIndustries/ForceSubscribeBot#2]
![IMG_20220326_111712](https://user-images.githubusercontent.com/99683540/160225834-788169e9-acb0-4a98-bc78-8d4823f9a557.jpg)

This is channel id or user id?

**Comment by Jisin0** [comment]
User obviously

**Comment by ShivangKakkar** [comment]
Thanks @Jisin0 for helping them.
